# Generated by Django 3.0.4 on 2020-05-01 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(db_column='cat_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='cat_nom', max_length=30, verbose_name='Nombre Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'db_table': 't_categoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(db_column='prod_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='prod_nom', max_length=25, verbose_name='Nombre Producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 't_producto',
            },
        ),
    ]
